### ISSUE TITLE
v1.1.0 won't start on Raspberry Pi 4

### ISSUE THREAD

**Issue by sprouse** [thevoltagesource/eagle-mqtt-bridge#11]
v1.1.0 won't start and gives this error message:
```
#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ebac54c
```

I rolled back v1.0.0 and it works fine.

**Comment by thevoltagesource** [comment]
I jumped from Node12 to Node16 with the 1.1.0 image. Can you try using the image with tag 'rpi4-12' so we can see if the issue goes away by reverting back to Node12?  This adds another reason I need to go buy a rPI4.

**Comment by sprouse** [comment]
rpi4-12 is working with no issues.
I searched for any reports of `16-alpine` having issues on RPI4 but did not find any.

**Comment by thevoltagesource** [comment]
I finally picked up a Pi4 and dug in to the issue.   The problem is a change with Alpine 3.13 and compatibility with older versions of Docker and libseccomp2.  The Docker compatibility will hit Pi3 and Pi4 users, where the library issue affects Raspbian on Pi4.  I found a [blog post](https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/?utm_source=pocket_mylist) that describes the issue as we as another project on GitHub with [similar findings](https://github.com/Koenkk/zigbee2mqtt/issues/7662).

By default Node builds the v16 images on Alpine 3.13 but they also have images based on Alpine 3.12.  For now I have moved the to the older base images so things work for everyone.  Hopefully Rasbian will get the needed updates to regain compatibility and eventually everyone will move to a newer version of Docker.

Give 1.2.0 a test when you have a chance.
