### ISSUE TITLE
Does the bridge hang if the MQTT broker goes offline?

### ISSUE THREAD

**Issue by sprouse** [thevoltagesource/eagle-mqtt-bridge#9]
I don't have any log info to help to determine if this is a bug or not, but I want ask if this condition is handled:

If the MQTT broker/server goes offline for some time, will the bridge recover when the broker is restored?

If needed I can try to recreate the condition and capture any available log info.

**Comment by thevoltagesource** [comment]
It turns out that situation is not handled.

 I had a couple of instances last month where the bridge went offline and in looking at the logs all I was getting was a broken log message. I pushed a new version of the bridge that fixed the logging and was just going to wait to see if it happened again and what error was reported. But with your idea I accelerated the testing by shutting down my MQTT broker.  The new logs confirm that the bridge fails if the MQTT broker is unavailable for more than a few seconds.  It recovers if it is just a brief interruption like a container restart but any longer and it gets stuck.

I will work on properly handling this situation.  Thanks for pointing this out.

**Comment by thevoltagesource** [comment]
It turns out the NodeJS MQTT client has a built in feature to reconnect by default.  The issue was that the demo code I used to implement the client killed the client if an error occurred. I changed the error handling to just log the error and the bridge will now successfully reconnect once the broker is back online.  I tested with the broker down for two minutes and it works.  

Let me know if it works for you as well.  The new docker container is available with tag 1.0.0 or latest.

**Comment by thevoltagesource** [comment]
@sprouse I haven't had any reconnect issues with the new build.  Is everything working properly for you now?

**Comment by sprouse** [comment]
Hi Jacob,
I’ve been away for a week. I’ll see if I can pull the new code tonight and test it.
Thanks!

Steven

**Comment by sprouse** [comment]
I downloaded the latest image and tested it by taking the MQTT broker offline for 10 minutes. 
The eagle bridge resumed with no problems.
I think this can be closed.
Thanks!
Steven

**Comment by sprouse** [comment]
Bridge resumes after MQTT broker comes back online.
